# Generated by Django 5.2 on 2025-04-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParserTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('heuristic', models.BooleanField(default=False)),
                ('frequent_pattern', models.BooleanField(default=False)),
                ('clustering', models.BooleanField(default=False)),
                ('ml', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=100)),
                ('log_format', models.TextField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='configparam.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Hyperparameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('default', models.FloatField()),
                ('parser_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configparam.parsertool')),
            ],
        ),
        migrations.CreateModel(
            name='RegexPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.TextField()),
                ('log_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configparam.logconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SettingParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('hyperparameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configparam.hyperparameter')),
                ('log_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configparam.logconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SizeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('file_log', models.CharField(max_length=255)),
                ('ground_truth', models.CharField(blank=True, max_length=255)),
                ('template', models.CharField(blank=True, max_length=255)),
                ('log_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configparam.logconfig')),
            ],
        ),
    ]
